// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20211029184724_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 4,
                            Gender = "Male",
                            Name = "Hobbs",
                            Species = "Tiger"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 5,
                            Gender = "Male",
                            Name = "Scooby-Doo",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 5,
                            Gender = "Female",
                            Name = "Nala",
                            Species = "Tiger"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 4,
                            Gender = "Female",
                            Name = "Minnie",
                            Species = "Mouse"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 2,
                            Gender = "Male",
                            Name = "Speedy Gonzales",
                            Species = "Mouse"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
